In [5]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

# Data Pre processing

In [9]:
stock_train= pd.read_csv('Google_Stock_Price_Train.csv')


In [10]:
stock_train.head()

Date    Open    High     Low   Close      Volume
0  1/3/2012  325.25  332.83  324.97  663.59   7,380,500
1  1/4/2012  331.27  333.87  329.08  666.45   5,749,400
2  1/5/2012  329.83  330.75  326.89  657.21   6,590,300
3  1/6/2012  328.34  328.77  323.68  648.24   5,405,900
4  1/9/2012  322.04  322.29  309.46  620.76  11,688,800

In [11]:
#in this we are going to predict the stock price for begining of a finiancfial day

In [19]:
stock_training_set = stock_train.iloc[:,1:2].values #this will create a numpy array as we know

In [20]:
stock_training_set

array([[325.25],
       [331.27],
       [329.83],
       ...,
       [793.7 ],
       [783.33],
       [782.75]])

# Feature Scaling 

In [14]:
from sklearn.preprocessing import MinMaxScaler
#for stock price prediction we will be using normalization formula 

In [16]:
sc = MinMaxScaler(feature_range = (0,1))
#now we will be applying the sc object to our data to effictively apply this normalization

In [17]:
stock_training_set_scaled = sc.fit_transform(stock_training_set)
#here fit means that we are going to take the min and max and apply it to the normalization formula

In [18]:
stock_training_set_scaled

array([[0.08581368],
       [0.09701243],
       [0.09433366],
       ...,
       [0.95725128],
       [0.93796041],
       [0.93688146]])

In [21]:
#now we are going to implement a data structure specifying what RNN needs to remember when predicting the next stock-
#-price,this is called number of time steps

In [22]:
#we will create a data structure with 60 time steps and 1 output
#this means that at each time 't' the RNN will look at 60 stock price before time 't'. and based on the trend it is-
#-capturing during these 60 privious time steps it will try to predict the output. 

In [23]:
#this simply means that our RNN will try to learn from the privious 60 days of stock price and it will learn the -
#-co-relation or some trends and based on its understanding it will try to predict the stock price. The Rnn will-
#-predict the stock price at time 't+1'.

In [24]:
#now we need to create two entities,
#x-train which will be the input of the RNN 
#y-train which will be the output
#here x train will contain the privious 60 financial days of stock price data and the y-train will give us the stock-
#-price of the next financial day


# Data structure to implement the above description

In [26]:
x_train = []
y_train = []
for i in range(60,1258):
    x_train.append(stock_training_set_scaled[i-60:i,0])
    y_train.append(stock_training_set_scaled[i,0])
    #as these are list,we need to convert them to numpy array as so the RNN will accept the data
x_train,y_train = np.array(x_train),np.array(y_train)

In [27]:
x_train

array([[0.08581368, 0.09701243, 0.09433366, ..., 0.07846566, 0.08034452,
        0.08497656],
       [0.09701243, 0.09433366, 0.09156187, ..., 0.08034452, 0.08497656,
        0.08627874],
       [0.09433366, 0.09156187, 0.07984225, ..., 0.08497656, 0.08627874,
        0.08471612],
       ...,
       [0.92106928, 0.92438053, 0.93048218, ..., 0.95475854, 0.95204256,
        0.95163331],
       [0.92438053, 0.93048218, 0.9299055 , ..., 0.95204256, 0.95163331,
        0.95725128],
       [0.93048218, 0.9299055 , 0.93113327, ..., 0.95163331, 0.95725128,
        0.93796041]])

In [28]:
#here 0.08581368 is the stock price of 60th day followed by privious 60 days of stock price
#here 0.09701243 is the stock price of 61st day followed by privious 60 days of stock price

In [29]:
y_train


array([0.08627874, 0.08471612, 0.07454052, ..., 0.95725128, 0.93796041,
       0.93688146])

In [30]:
#now we will be adding dimension. this dimension we will add is exactly a unit i.e the number of predictors we can-
#-use to predict what we want i.e the stock price at time step t+1

In [31]:
#for adding new dimension we use reshape function

In [32]:
x_train = np.reshape(x_train,(x_train.shape[0],x_train.shape[1],1))

# Building The RNN

In [ ]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Dropout

In [1]:
regressor = Sequential() #this will represent the sequence of layers

NameError: name 'Sequential' is not defined